# Uncomment the next line to define a global platform for your project
platform :ios, '14.2'

target 'MyContactBook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GIFImageView'

  # Pods for MyContactBook

  target 'MyContactBookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyContactBookUITests' do
    # Pods for testing
  end

end
